added functions.js
htmlacademy-javascript/2323243-kekstagram-28 pull request #3
Opened 2023-02-21 15:56 UTC by GermanBurdin1

функции закомментировал

2023-02-22 14:41 UTC, 0snilcy requested changes

2023-02-22 14:41 UTC, 0snilcy commented on index.html
> +<script src="C:\Users\User\Desktop\Войти в IT\keksogram\2323243-kekstagram-28\js\functions.js"></script>
Скрипт должн быть подключен относительно
https://htmlacademy.ru/blog/html/links

2023-02-22 14:41 UTC, 0snilcy commented on js/functions.js
> +//1. Функция длины строки
Почему весь код в комментарии? Должно быть обычным кодом

2023-02-24 12:40 UTC, GermanBurdin1 commented on js/functions.js
> +//1. Функция длины строки
Изменил

2023-02-25 14:34 UTC, merged